# Originally from: https://github.com/arulrajnet/uptime-kuma-subfolder-compose
# The port was modified from 8080 to 4000
# This is a workaround to enable uptime-kuma to be hosted behind a proxy
# Uptime-kuma and an nginx server are installed in the same container and are proxied
# to by the host systems nginx server. This allows uptime-kuma to be accessed at /kuma 
# from the host systems IP address

upstream kuma_service {
    keepalive 32; # keepalive connections
    server kuma:3001; # upstream ip and port
}

server {
    listen 4000 default_server;
    server_name localhost;

    # Kuma service configuration
    location /kuma {
        # Strip /kuma prefix
        rewrite ^/kuma/?(.*)$ /$1 break;

        # Proxy to upstream service
        proxy_pass http://kuma_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Response header manipulation - add /kuma prefix to Location headers
        proxy_redirect ~^/(.*)$ /kuma/$1;
    }
}