---
- name: Configure UFW for webservers
  hosts: labproject
  become: true
  become_method: sudo
  
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/maks/.ssh/project-ssh-key
  
  # firewall rules for web servers
  tasks:
    - name: Reset UFW Firewall
      community.general.ufw:
        state: reset

    - name: Add Default deny incoming rule
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Add Default allow outgoing rule
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Allow SSH Access
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP Access
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow HTTPS Access
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp
    
    # might not be needed anymore
    - name: Allow Node Exporter
      community.general.ufw:
        rule: allow
        port: "9100"
        proto: tcp
    
    # might not be needed anymore
    - name: Allow Nginx Exporter
      community.general.ufw:
        rule: allow
        port: "9113"
        proto: tcp

    - name: Allow Prometheus web interface access
      community.general.ufw:
        rule: allow
        port: "9090"
        proto: tcp

    - name: Allow access to grafana web interface
      community.general.ufw:
        rule: allow
        port: "3000"
        proto: tcp

    - name: Allow Uptime-Kuma Access
      community.general.ufw:
        rule: allow
        port: "3001"
        proto: tcp

    - name: Allow loki Access
      community.general.ufw:
        rule: allow
        port: "3100"
        proto: tcp

    - name: Allow alloy status
      community.general.ufw:
        rule: allow
        port: "12345"
        proto: tcp

    - name: Enable UFW Firewall Service
      community.general.ufw:
        state: enabled
  