---
- name: Configure UFW for webservers
  hosts: labproject
  become: true
  become_method: sudo
  
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: /home/maks/.ssh/project-ssh-key
    hostonly_interface: enp0s8
    
  # firewall rules for web servers
  tasks:
    - name: Reset UFW Firewall
      community.general.ufw:
        state: reset

    - name: Add Default deny incoming rule
      community.general.ufw:
        direction: incoming
        policy: deny

    - name: Add Default allow outgoing rule
      community.general.ufw:
        direction: outgoing
        policy: allow

    - name: Allow SSH Access
      community.general.ufw:
        rule: allow
        port: "22"
        proto: tcp

    - name: Allow HTTP Access
      community.general.ufw:
        rule: allow
        port: "80"
        proto: tcp

    - name: Allow HTTPS Access
      community.general.ufw:
        rule: allow
        port: "443"
        proto: tcp
    
    # need to allow access to logging because uptime-kuma is running in a docker container
    - name: Allow restricted services on all interfaces
      community.general.ufw:
        rule: allow
        port: "3100"
        proto: tcp

    # need to allow access to logging because uptime-kuma is running in a docker container
    - name: Allow restricted services on all interfaces
      community.general.ufw:
        rule: allow
        port: "9090"
        proto: tcp
  
    # block direct access to logging servers (prometheus and loki)
    - name: Deny loki access on VirtualBox host-only interface
      community.general.ufw:
        rule: deny
        direction: in
        interface: "{{ hostonly_interface }}"
        port: "3100"
        proto: tcp

    # block direct access to logging servers (prometheus and loki)
    - name: Deny prometheus access on VirtualBox host-only interface
      community.general.ufw:
        rule: deny
        direction: in
        interface: "{{ hostonly_interface }}"
        port: "9090"
        proto: tcp

    - name: Enable UFW Firewall Service
      community.general.ufw:
        state: enabled
  